
package com.lilzh.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.lilzh.webservice.business.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Business", targetNamespace = "http://business.webservice.lilzh.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Business {


    /**
     * 
     * @param param
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://business.webservice.lilzh.com/", className = "com.lilzh.webservice.business.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://business.webservice.lilzh.com/", className = "com.lilzh.webservice.business.EchoResponse")
    public String echo(
        @WebParam(name = "param", targetNamespace = "")
        String param);

}
