CREATE TABLE user_account(
    Id INTEGER NOT NULL AUTO_INCREMENT COMMENT 'ID',
    Username VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名',
    Mobile VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手机号码',
    QQ VARCHAR(16) NOT NULL DEFAULT '' COMMENT 'QQ号',
    WechatOpenId VARCHAR(128) NOT NULL DEFAULT '' COMMENT '微信OpenAPI',
    Mail VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
    Password VARCHAR(64) NOT NULL DEFAULT '' COMMENT '密码',
    Status INTEGER NOT NULL DEFAULT 0 COMMENT '状态，1正常，2禁止登录，3删除',
    EnterpriseVerifyStatus INTEGER NOT NULL DEFAULT 0 COMMENT '企业认证状态，0未认证，1认证成功，2认证中，3认证被拒绝，4认证被删除',
    AuthorizationVerifyStatus INTEGER NOT NULL DEFAULT 0 COMMENT '授权分销商认证状态，0未认证，1认证成功，2认证中，3认证被拒绝，4认证被删除',
    Type INTEGER NOT NULL DEFAULT 0 COMMENT '类型，1 终端用户 2 小B 3 大B',
    ProfileType INTEGER NOT NULL DEFAULT 0 COMMENT '统计类型，1 全新用户 其他待定',
    Source INTEGER NOT NULL DEFAULT 0 COMMENT '注册平台，1为PC',
    Description VARCHAR(64) NOT NULL DEFAULT '' COMMENT '描述',
    AddUserId INTEGER NOT NULL DEFAULT 0 COMMENT '添加用户ID',
    SaleName VARCHAR(32) NOT NULL DEFAULT '' COMMENT '销售负责人',
    LastEditor VARCHAR(16) NOT NULL DEFAULT '' COMMENT '最后更新用户',
    AddTime DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT '记录时间',
    UpdateTime TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (Id),
    UNIQUE KEY UK_Username(Username),
    UNIQUE KEY UK_Mobile(Mobile),
    INDEX IX_Mail(Mail),
    INDEX IX_AddTime(AddTime),
    INDEX IX_UpdateTime(UpdateTime)
) Engine = InnoDB COMMENT '账户';