CREATE TABLE person
(
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  first_name VARCHAR(20) NOT NULL DEFAULT '' COMMENT '名字',
  last_name VARCHAR(20) NOT NULL DEFAULT '' COMMENT '姓氏',
  gender ENUM('M', 'F') NOT NULL DEFAULT 'M' COMMENT '性别',      -- 枚举类型
  birth_day DATE NOT NULL DEFAULT '1000-01-01' COMMENT '出生年月',
  street VARCHAR(30) NOT NULL DEFAULT '' COMMENT '街道',
  city VARCHAR(20) NOT NULL DEFAULT '' COMMENT '城市',
  state VARCHAR(20) NOT NULL DEFAULT '' COMMENT '州',
  country VARCHAR(20) NOT NULL DEFAULT '' COMMENT '国家',
  postal_code VARCHAR(20) NOT NULL DEFAULT '' COMMENT '邮编',
  update_time TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',  -- timestamp可以指定当时时间
  CONSTRAINT PK_PERSON PRIMARY KEY (id),
  INDEX IX_POSTAL_CODE(postal_code)
) Engine = InnoDB COMMENT '个人';

CREATE TABLE favourite_food
(
  person_id SMALLINT UNSIGNED COMMENT '个人ID',
  food VARCHAR(20) NOT NULL DEFAULT '' COMMENT '食物',
  update_time TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT PK_FAVOURITE_FOOD PRIMARY KEY (person_id, food),
  CONSTRAINT FK_FAV_FOOD_PERSON_ID FOREIGN KEY (person_id) REFERENCES person(id)    -- 外键约束只在InnoDB起作用
) Engine = InnoDB COMMENT '喜爱的食物'